---
title: My projects
search: false
---


Academic papers

- Callens, A., Morichon, D., Liria, P., Epelde, I., & Liquet, B. (2021). Automatic Creation of Storm Impact Database Based on Video Monitoring and Convolutional Neural Networks. Remote Sensing, 13(10), 1933, (<a href="https://doi.org/10.3390/rs13101933" target="_blank">10.3390/rs13101933</a>).

- Callens, A., Morichon, D., Abadie, S., Delpey, M., Liquet, B. (2020).  Applied Ocean Research, 104, 
(<a href="https://doi.org/10.1016/j.apor.2020.102339" target="_blank">10.1016/j.apor.2020.102339</a>).

- Callens, A., Wang, Y., Fu, L. et al. (2020). Robust Estimation Procedure for Autoregressive Models with Heterogeneity. Environmental Modeling & Assessment, ( <a href="https://doi.org/10.1007/s10666-020-09730-w" target="_blank">10.1007/s10666-020-09730-w</a>).

- Morichon, D., de Santiago, I., Delpey, M., Somdecoste, T., Callens, A., Liquet, B., ... & Arnould, P. (2018). Assessment of flooding hazards at an engineered beach during extreme events: Biarritz, SW France. Journal of Coastal Research, 85(sp1), 801-805, ( <a href="https://doi.org/10.2112/SI85-161.1" target="_blank">10.2112/SI85-161.1</a>).

My thesis report

- *PhD thesis*: <a href="http://www.theses.fr/2021PAUU3016" target="_blank"> Statistical learning for coastal risks assessment</a>

- *Master 2 Thesis*: <a href="/doc/Master_thesis_2_Callens_Aurelien.pdf" target="_blank"> Robust regression for time series exhibiting heterogeneity</a>

- *Master 1 Thesis*: <a href="/doc/Master_thesis_1_Callens_Aurelien.pdf" target="_blank"> Analysis of physical and climatic forcings impacting the transport of micropollutants in the Adour estuary (French version)</a>. 

Shiny applications 

- <a href="https://aureliencallens.shinyapps.io/application/" target="_blank">My first amazing (but laggy) Shiny application</a> summarizing a part of my first internship (master 1).

- <a href="https://aureliencallens.shinyapps.io/Dummy_angler_app/" target="_blank">Dummy example of the fishing application I use </a>

- <a href="https://aureliencallens.shinyapps.io/Fishing_analysis/" target="_blank">Shiny application presenting the results of my fishing season 2021</a>

Rpackage
- Involved in the development of `rlmDataDriven` package (available on CRAN), especially: 
    + `rlmDD_het.R` : this function performs a robust regression which accounts for temporal correlations and heterogeneity.
    + `whm.R` : this function is the R implementation of the weighted M-estimation.


```{=html}
<style>

#hero-banner {
  padding-top: 35px;
  background-color: rgb(237,243,249);
}

#quarto-content main { 
  margin-top: 0;
  padding-top: 0;
}

html {
  scroll-behavior: smooth;
}

.headline {
  font-size: 1.25em;
  font-weight: 300;
  padding-bottom: 1em;
}

.headline p {
  margin: 0;
  padding-bottom: 0.2rem;
}

.headline a {
  text-decoration: none;
}

.headline ul li {
  margin-bottom: 0.3em;
}

.carousel.card {
  padding-top: 2em;
}

.carousel img {
  width: 70%;
  margin-bottom: 110px;
}

.carousel-control-prev-icon, .carousel-control-next-icon {
  margin-bottom: 110px;
}

.carousel-caption {
  padding-top: 1em;
}

.touch {
  
}
</style>
```
